version: '3.9'
services:
  mysql_cham_container:
    restart: always
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 23306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis_cham_container:
    restart: always
    image: redis:7
    ports:
     - 26379:6379
    volumes:
     - ./data/redis:/data

# volumes:
#   mysql_data:
#   redis_data:
