version: '3.7'
services:
  mysql_cham_container:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 23306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    restart: always
    image: redis:5
    ports:
     - 26379:6379
    volumes:
     - redis_data:/data

volumes:
  mysql_data:
  redis_data:
